### ISSUE TITLE
Undefined error

### ISSUE THREAD

**Issue by aleph0ne** [nvsoft/talib#3]
Any idea why this error is happening and/or how to fix it?

`undefined: "github.com/sumorf/talib".Ma`

Happens with all indicators.  For example, `talib.CdlShootingStar(openPrices, highPrices, lowPrices, closePrices)` also gives an error: `undefined: "github.com/sumorf/talib".CdlShootingStar`

**Comment by f0cii** [comment]
This is a mistake. should be:

"github.com/frankrap/talib"

**Comment by aleph0ne** [comment]
Same problem.

```
import "github.com/frankrap/talib"

// set prices based on price feed for openPrices, etc..
//
star := talib.CdlShootingStar(openPrices, highPrices, lowPrices, closePrices)

```
results in 

`srcfile:x:y: undefined: "github.com/frankrap/talib".CdlShootingStar`

**Comment by f0cii** [comment]
What operating system do you use? only windows and linux are supported.

**Comment by aleph0ne** [comment]
I run Linux. I'm on an Intel system, running Arch Linux (Manjaro). talib compiles and works perfectly. Not sure why the above is happening. I'm using `go version go1.15.8 linux/amd64`
